USE MYSQL_DATABASE;

CREATE TABLE IF NOT EXISTS Accounts(
	A_ID INT PRIMARY KEY AUTO_INCREMENT,
	U_NAME VARCHAR(30),
    P_WORD INT,
    MY_SALT VARCHAR(255)
);

CREATE TABLE Contact_Info(
	CI_ID INT PRIMARY KEY AUTO_INCREMENT,
    Street VARCHAR(255),
    City VARCHAR(255),
    State VARCHAR(2),
    Zip VARCHAR(5),
    Phone VARCHAR(10),
    Email VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS Customer (
	C_ID INT PRIMARY KEY AUTO_INCREMENT,
	F_NAME VARCHAR(50),
    L_NAME VARCHAR(255),
	CI_ID INT,
	FOREIGN KEY (CI_ID) REFERENCES Contact_Info(CI_ID)
);

CREATE TABLE IF NOT EXISTS Restaurant(
	R_ID INT PRIMARY KEY AUTO_INCREMENT,
    R_Name VARCHAR(50),
    CI_ID INT,
    FOREIGN KEY(CI_ID) REFERENCES Contact_Info(CI_ID)
);

CREATE TABLE IF NOT EXISTS Manager(
	M_ID INT PRIMARY KEY AUTO_INCREMENT,
    R_ID INT,
    FOREIGN KEY (R_ID) REFERENCES Restaurant(R_ID)
);

CREATE TABLE IF NOT EXISTS Food_Item (
	MI_ID INT PRIMARY KEY AUTO_INCREMENT,
	MI_NAME VARCHAR(50),
	MI_Description VARCHAR(255),
    Price float,
    R_ID INT,
    MI_Special BOOLEAN,
    Sold_out BOOLEAN,
    FOREIGN KEY (R_ID) REFERENCES Restaurant(R_ID)
);

CREATE TABLE IF NOT EXISTS Invoice(
	Inv_ID INT PRIMARY KEY AUTO_INCREMENT,
    Total DOUBLE,
    C_ID INT,
    FOREIGN KEY (C_ID) REFERENCES Customer(C_ID)
);

CREATE TABLE IF NOT EXISTS Invoice_Item(
	I_ID INT PRIMARY KEY AUTO_INCREMENT,
    MI_ID INT,
    Quantity INT,
    Inv_ID INT,
    FOREIGN KEY (MI_ID) REFERENCES Food_Item(MI_ID),
    FOREIGN KEY (Inv_ID) REFERENCES Invoice(Inv_ID)
);